// Generated by using Rcpp::compileAttributes() -> do not edit by hand
// Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#include <Rcpp.h>

using namespace Rcpp;

// GetXrefFromString
Rcpp::DataFrame GetXrefFromString(const std::string& p_file_name);
RcppExport SEXP _PDFR_GetXrefFromString(SEXP p_file_nameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type p_file_name(p_file_nameSEXP);
    rcpp_result_gen = Rcpp::wrap(GetXrefFromString(p_file_name));
    return rcpp_result_gen;
END_RCPP
}
// GetXrefFromRaw
Rcpp::DataFrame GetXrefFromRaw(const std::vector<uint8_t>& p_raw_file);
RcppExport SEXP _PDFR_GetXrefFromRaw(SEXP p_raw_fileSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::vector<uint8_t>& >::type p_raw_file(p_raw_fileSEXP);
    rcpp_result_gen = Rcpp::wrap(GetXrefFromRaw(p_raw_file));
    return rcpp_result_gen;
END_RCPP
}
// GetObjectFromString
Rcpp::List GetObjectFromString(const std::string& p_file_name, int p_object_number);
RcppExport SEXP _PDFR_GetObjectFromString(SEXP p_file_nameSEXP, SEXP p_object_numberSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type p_file_name(p_file_nameSEXP);
    Rcpp::traits::input_parameter< int >::type p_object_number(p_object_numberSEXP);
    rcpp_result_gen = Rcpp::wrap(GetObjectFromString(p_file_name, p_object_number));
    return rcpp_result_gen;
END_RCPP
}
// GetObjectFromRaw
Rcpp::List GetObjectFromRaw(const std::vector<uint8_t>& p_raw_file, int p_object_number);
RcppExport SEXP _PDFR_GetObjectFromRaw(SEXP p_raw_fileSEXP, SEXP p_object_numberSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::vector<uint8_t>& >::type p_raw_file(p_raw_fileSEXP);
    Rcpp::traits::input_parameter< int >::type p_object_number(p_object_numberSEXP);
    rcpp_result_gen = Rcpp::wrap(GetObjectFromRaw(p_raw_file, p_object_number));
    return rcpp_result_gen;
END_RCPP
}
// GetPdfPageFromString
Rcpp::List GetPdfPageFromString(const std::string& p_file_name, int p_page_number, bool p_each_glyph);
RcppExport SEXP _PDFR_GetPdfPageFromString(SEXP p_file_nameSEXP, SEXP p_page_numberSEXP, SEXP p_each_glyphSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type p_file_name(p_file_nameSEXP);
    Rcpp::traits::input_parameter< int >::type p_page_number(p_page_numberSEXP);
    Rcpp::traits::input_parameter< bool >::type p_each_glyph(p_each_glyphSEXP);
    rcpp_result_gen = Rcpp::wrap(GetPdfPageFromString(p_file_name, p_page_number, p_each_glyph));
    return rcpp_result_gen;
END_RCPP
}
// GetPdfPageFromRaw
Rcpp::List GetPdfPageFromRaw(const std::vector<uint8_t>& p_raw_file, int p_page_number, bool p_atoms);
RcppExport SEXP _PDFR_GetPdfPageFromRaw(SEXP p_raw_fileSEXP, SEXP p_page_numberSEXP, SEXP p_atomsSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::vector<uint8_t>& >::type p_raw_file(p_raw_fileSEXP);
    Rcpp::traits::input_parameter< int >::type p_page_number(p_page_numberSEXP);
    Rcpp::traits::input_parameter< bool >::type p_atoms(p_atomsSEXP);
    rcpp_result_gen = Rcpp::wrap(GetPdfPageFromRaw(p_raw_file, p_page_number, p_atoms));
    return rcpp_result_gen;
END_RCPP
}
// GetGlyphMap
Rcpp::DataFrame GetGlyphMap(const std::string& p_file_name, int p_page_number);
RcppExport SEXP _PDFR_GetGlyphMap(SEXP p_file_nameSEXP, SEXP p_page_numberSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type p_file_name(p_file_nameSEXP);
    Rcpp::traits::input_parameter< int >::type p_page_number(p_page_numberSEXP);
    rcpp_result_gen = Rcpp::wrap(GetGlyphMap(p_file_name, p_page_number));
    return rcpp_result_gen;
END_RCPP
}
// GetPageStringFromString
std::string GetPageStringFromString(const std::string& p_file_name, int p_page_number);
RcppExport SEXP _PDFR_GetPageStringFromString(SEXP p_file_nameSEXP, SEXP p_page_numberSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type p_file_name(p_file_nameSEXP);
    Rcpp::traits::input_parameter< int >::type p_page_number(p_page_numberSEXP);
    rcpp_result_gen = Rcpp::wrap(GetPageStringFromString(p_file_name, p_page_number));
    return rcpp_result_gen;
END_RCPP
}
// GetPageStringFromRaw
std::string GetPageStringFromRaw(const std::vector<uint8_t>& p_raw_file, int p_page_number);
RcppExport SEXP _PDFR_GetPageStringFromRaw(SEXP p_raw_fileSEXP, SEXP p_page_numberSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::vector<uint8_t>& >::type p_raw_file(p_raw_fileSEXP);
    Rcpp::traits::input_parameter< int >::type p_page_number(p_page_numberSEXP);
    rcpp_result_gen = Rcpp::wrap(GetPageStringFromRaw(p_raw_file, p_page_number));
    return rcpp_result_gen;
END_RCPP
}
// GetPdfDocumentFromString
Rcpp::DataFrame GetPdfDocumentFromString(const std::string& p_file_name);
RcppExport SEXP _PDFR_GetPdfDocumentFromString(SEXP p_file_nameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type p_file_name(p_file_nameSEXP);
    rcpp_result_gen = Rcpp::wrap(GetPdfDocumentFromString(p_file_name));
    return rcpp_result_gen;
END_RCPP
}
// GetPdfDocumentFromRaw
Rcpp::DataFrame GetPdfDocumentFromRaw(const std::vector<uint8_t>& p_file_name);
RcppExport SEXP _PDFR_GetPdfDocumentFromRaw(SEXP p_file_nameSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::vector<uint8_t>& >::type p_file_name(p_file_nameSEXP);
    rcpp_result_gen = Rcpp::wrap(GetPdfDocumentFromRaw(p_file_name));
    return rcpp_result_gen;
END_RCPP
}
// GetPdfBoxesFromString
Rcpp::DataFrame GetPdfBoxesFromString(const std::string& p_file_name, int p_page_number);
RcppExport SEXP _PDFR_GetPdfBoxesFromString(SEXP p_file_nameSEXP, SEXP p_page_numberSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::string& >::type p_file_name(p_file_nameSEXP);
    Rcpp::traits::input_parameter< int >::type p_page_number(p_page_numberSEXP);
    rcpp_result_gen = Rcpp::wrap(GetPdfBoxesFromString(p_file_name, p_page_number));
    return rcpp_result_gen;
END_RCPP
}
// GetPdfBoxesFromRaw
Rcpp::DataFrame GetPdfBoxesFromRaw(const std::vector<uint8_t>& p_file_name, int p_page_number);
RcppExport SEXP _PDFR_GetPdfBoxesFromRaw(SEXP p_file_nameSEXP, SEXP p_page_numberSEXP) {
BEGIN_RCPP
    Rcpp::RObject rcpp_result_gen;
    Rcpp::RNGScope rcpp_rngScope_gen;
    Rcpp::traits::input_parameter< const std::vector<uint8_t>& >::type p_file_name(p_file_nameSEXP);
    Rcpp::traits::input_parameter< int >::type p_page_number(p_page_numberSEXP);
    rcpp_result_gen = Rcpp::wrap(GetPdfBoxesFromRaw(p_file_name, p_page_number));
    return rcpp_result_gen;
END_RCPP
}
// stopCpp
void stopCpp();
RcppExport SEXP _PDFR_stopCpp() {
BEGIN_RCPP
    Rcpp::RNGScope rcpp_rngScope_gen;
    stopCpp();
    return R_NilValue;
END_RCPP
}

RcppExport SEXP run_testthat_tests();

static const R_CallMethodDef CallEntries[] = {
    {"_PDFR_GetXrefFromString", (DL_FUNC) &_PDFR_GetXrefFromString, 1},
    {"_PDFR_GetXrefFromRaw", (DL_FUNC) &_PDFR_GetXrefFromRaw, 1},
    {"_PDFR_GetObjectFromString", (DL_FUNC) &_PDFR_GetObjectFromString, 2},
    {"_PDFR_GetObjectFromRaw", (DL_FUNC) &_PDFR_GetObjectFromRaw, 2},
    {"_PDFR_GetPdfPageFromString", (DL_FUNC) &_PDFR_GetPdfPageFromString, 3},
    {"_PDFR_GetPdfPageFromRaw", (DL_FUNC) &_PDFR_GetPdfPageFromRaw, 3},
    {"_PDFR_GetGlyphMap", (DL_FUNC) &_PDFR_GetGlyphMap, 2},
    {"_PDFR_GetPageStringFromString", (DL_FUNC) &_PDFR_GetPageStringFromString, 2},
    {"_PDFR_GetPageStringFromRaw", (DL_FUNC) &_PDFR_GetPageStringFromRaw, 2},
    {"_PDFR_GetPdfDocumentFromString", (DL_FUNC) &_PDFR_GetPdfDocumentFromString, 1},
    {"_PDFR_GetPdfDocumentFromRaw", (DL_FUNC) &_PDFR_GetPdfDocumentFromRaw, 1},
    {"_PDFR_GetPdfBoxesFromString", (DL_FUNC) &_PDFR_GetPdfBoxesFromString, 2},
    {"_PDFR_GetPdfBoxesFromRaw", (DL_FUNC) &_PDFR_GetPdfBoxesFromRaw, 2},
    {"_PDFR_stopCpp", (DL_FUNC) &_PDFR_stopCpp, 0},
    {"run_testthat_tests",             (DL_FUNC) &run_testthat_tests,             0},
    {NULL, NULL, 0}
};

RcppExport void R_init_PDFR(DllInfo *dll) {
    R_registerRoutines(dll, NULL, CallEntries, NULL, NULL);
    R_useDynamicSymbols(dll, FALSE);
}
