# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

.get_xref <- function(filename) {
    .Call(`_PDFR_get_xref`, filename)
}

.get_xrefraw <- function(rawfile) {
    .Call(`_PDFR_get_xrefraw`, rawfile)
}

.get_obj <- function(filename, o) {
    .Call(`_PDFR_get_object`, filename, o)
}

.get_objraw <- function(rawfile, o) {
    .Call(`_PDFR_get_objectraw`, rawfile, o)
}

.pdfpage <- function(filename, pagenum, g) {
    .Call(`_PDFR_pdfpage`, filename, pagenum, g)
}

.pdfpageraw <- function(rawfile, pagenum, g) {
    .Call(`_PDFR_pdfpageraw`, rawfile, pagenum, g)
}

.getglyphmap <- function(s, pagenum) {
    .Call(`_PDFR_getglyphmap`, s, pagenum)
}

.pagestring <- function(s, pagenum) {
    .Call(`_PDFR_pagestring`, s, pagenum)
}

.pagestringraw <- function(rawfile, pagenum) {
    .Call(`_PDFR_pagestringraw`, rawfile, pagenum)
}

.pdfdoc <- function(s) {
    .Call(`_PDFR_pdfdoc`, s)
}

.pdfdocraw <- function(s) {
    .Call(`_PDFR_pdfdocraw`, s)
}

.stopCpp <- function() {
    invisible(.Call(`_PDFR_stopCpp`))
}

pdfpolygons <- function(s, pagenum) {
    .Call(`_PDFR_pdfpolygons`, s, pagenum)
}

pdfboxes <- function(s, pagenum) {
    .Call(`_PDFR_pdfboxes`, s, pagenum)
}

