# Generated by using Rcpp::compileAttributes() -> do not edit by hand
# Generator token: 10BE3573-1514-4C36-9D1C-5A225CD40393

#' Rex
#'
#' Return substrings matching a given pattern
#'
#' @param strvec The string(s) to be searched
#' @param matcher The regular expression to be matched
#' @export
Rex <- function(strvec, matcher) {
    .Call('_PDFR_Rex', PACKAGE = 'PDFR', strvec, matcher)
}

#' rc4
#'
#' Performs an RC4 hash for a given key
#'
#' @param msg The message to be hashed as a raw vector
#' @param key the raw vector with which to hash
#' @export
rc4 <- function(msg, key) {
    .Call('_PDFR_rc4', PACKAGE = 'PDFR', msg, key)
}

#' md5
#'
#' returns an md5 hash of a given raw vector as a raw vector
#'
#' @param input A raw vector
#' @export
md5 <- function(input) {
    .Call('_PDFR_md5', PACKAGE = 'PDFR', input)
}

#' Return the xref table from a PDF document
#'
#' Returns a data frame of objects and their byte positions in a pdf
#'
#' @param filename the path to a valid PDF file.
#' @export
get_xref <- function(filename) {
    .Call('_PDFR_get_xref', PACKAGE = 'PDFR', filename)
}

#' get_object
#'
#' Show the key:value pairs in a PDF object dictionary
#'
#' @param filename the path to a valid PDF file.
#' @param o The object number, given as an integer.
#' @export
get_object <- function(filename, o) {
    .Call('_PDFR_get_object', PACKAGE = 'PDFR', filename, o)
}

#' get_object_stream
#'
#' Get a pdf object's stream (if any)
#'
#' @param filename the path to a valid PDF file.
#' @param o The object number, given as an integer.
#' @export
get_obj_stream <- function(filename, o) {
    .Call('_PDFR_get_obj_stream', PACKAGE = 'PDFR', filename, o)
}

#' pdfdoc
#'
#' List a PDF document's filename, catalogue dictionary, page dictionaries,
#' encryption status and file key (if encrypted)
#'
#' @param filepath the path to a valid PDF file.
#' @export
pdfdoc <- function(filepath) {
    .Call('_PDFR_pdfdoc', PACKAGE = 'PDFR', filepath)
}

#' pdfpage
#'
#' Returns a list comprising a page's fonts, its Postscript program as a text
#' string and its text elements as an R data frame
#'
#' @param filename the path to a valid PDF file.
#' @param pagenum the page to extract
#' @export
pdfpage <- function(filename, pagenum) {
    .Call('_PDFR_pdfpage', PACKAGE = 'PDFR', filename, pagenum)
}

#' pdfpageraw
#'
#' Returns a list comprising a page's fonts, its Postscript program as a text
#' string and its text elements as an R data frame
#'
#' @param rawfile raw pdf data
#' @param pagenum the page to extract
#' @export
pdfpageraw <- function(rawfile, pagenum) {
    .Call('_PDFR_pdfpageraw', PACKAGE = 'PDFR', rawfile, pagenum)
}

